ctrl_interface=/run/wpa_supplicant
ctrl_interface_group=_wpas
update_config=1
eapol_version=1
ap_scan=1
fast_reauth=1

mac_addr=1
preassoc_mac_addr=1
gas_rand_mac_addr=1
country=XX
ext_password_backend=file:/etc/wpa_supplicant/wifi-passwords.conf

# use a second config file for wpa3 secrets
network={
	ssid="xxx"
	key_mgmt=SAE
	ieee80211w=2
}

network={
	ssid="eduroam"
	scan_ssid=1
	key_mgmt=WPA-EAP
	eap=PEAP
	identity="x@y"
#	anonymous_identity="anonymous@x"
#	ca_cert2="/etc/wpa_supplicant/eduroam.cer"
	phase1="tls_disable_tlsv1_3=0"
#	phase2="auth=PAP"
#	ocsp=1
	phase2="auth=MSCHAPV2"
	password=ext:pwd_eduroam
}

network={
	ssid="x"
	key_mgmt=SAE
	ieee80211w=2
	mac_addr=0
}
