#!/bin/sh
# input is kernel version, e.g. 6.7.3_1
set -e
VERSION="$2"
EFI="/boot"
UKI="initramfs-${VERSION}.img"

[ -x /usr/bin/sbctl ] || exit 0
[ -x /usr/bin/efibootmgr ] || exit 0

sbctl remove-file ${EFI}/${UKI}
hexnum=$(efibootmgr | grep "Void Linux (uki) with kernel ${VERSION}" | cut -c "5-8")
[ "${hexnum}" ] && efibootmgr -Bq -b ${hexnum}
